"""cyber_detectives.compat.javahash against the real JDK.

tests/fixtures/golden/javahash.json holds java.util.HashSet iteration orders recorded from
Temurin 8u504 under -XX:hashCode=2 by tools/reference/JavaHashProbe.java (regenerated by
tools/reference/regen_golden.sh). Set CD_JAVAHASH_LIVE=1 (with a reference build, see
tools/reference/README.md) to also re-run the probe against a live JDK.
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys

import pytest

from cyber_detectives.compat.javahash import (IDENTITY_HASH, JavaHashMap, JavaHashSet, java_hash_code,
                                              java_string_hash, spread)

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
FIXTURE = os.path.join(HERE, "fixtures", "golden", "javahash.json")


class Obj:
    """A key with identity hashCode/equals, like projects.cyberDetective.Vertex."""

    def __init__(self, label):
        self.label = label

    def __repr__(self):
        return self.label


def _digest(line):
    return hashlib.sha1(line.encode("utf-8")).hexdigest()[:12]


def _replay(script):
    objs = {}
    st = JavaHashSet()
    kind = script["kind"]

    def key(tok):
        if tok == "null":
            return None
        if kind == "obj":
            return objs.setdefault(tok, Obj(tok))
        return int(tok) if kind == "int" else tok

    def label(k):
        if k is None:
            return "null"
        return k.label if kind == "obj" else str(k)

    for i, op in enumerate(script["ops"]):
        k = key(op[1:])
        if op[0] == "+":
            st.add(k)
        else:
            st.remove(k)
        yield i, " ".join(label(x) for x in st)


def _scripts():
    with open(FIXTURE, encoding="ascii") as f:
        return json.load(f)


def test_fixture_header():
    d = _scripts()
    h = d["header"]
    assert h["jvm_flags"] == "-XX:+UnlockExperimentalVMOptions -XX:hashCode=2"
    assert h["identity_hash_of_two_objects"] == "1,1" == "%d,%d" % (IDENTITY_HASH, IDENTITY_HASH)
    assert h["num_ops"] == sum(len(s["ops"]) for s in d["scripts"]) > 10000


@pytest.mark.parametrize("script", _scripts()["scripts"], ids=lambda s: s["id"])
def test_iteration_order_matches_jdk(script):
    for i, line in _replay(script):
        assert _digest(line) == script["orders_sha1_12"][i], (
            "%s: order differs from the JDK after op %d (%s): python gives %r"
            % (script["id"], i, script["ops"][i], line))


def test_fixture_exercises_tree_bins():
    """The scripts must reach treeified bins, tree removals, untreeify and re-treeify."""
    import cyber_detectives.compat.javahash as jh

    counts = {"tree": 0, "remove": 0, "untreeify": 0}
    orig_make, orig_rm = jh._make_tree_bin, jh._remove_tree_node

    def make(*a):
        counts["tree"] += 1
        return orig_make(*a)

    def rm(*a):
        r = orig_rm(*a)
        counts["remove"] += 1
        counts["untreeify"] += bool(r)
        return r

    jh._make_tree_bin, jh._remove_tree_node = make, rm
    try:
        for s in _scripts()["scripts"]:
            for _ in _replay(s):
                pass
    finally:
        jh._make_tree_bin, jh._remove_tree_node = orig_make, orig_rm
    assert counts["tree"] > 20 and counts["remove"] > 1000 and counts["untreeify"] > 10, counts


# --------------------------------------------------------------------------- unit tests
# (expected orders recorded from Temurin 8u504, -XX:hashCode=2, JavaHashProbe)


def test_string_hash():
    assert java_string_hash("") == 0
    assert java_string_hash("a") == 97
    assert java_string_hash("Aa") == java_string_hash("BB") == 2112
    assert java_string_hash("polygenelubricants") == -2 ** 31  # Integer.MIN_VALUE
    assert java_string_hash("Å") == 0xC5
    assert java_string_hash("\U0001F600") == 0xD83D * 31 + 0xDE00  # two UTF-16 code units


def test_hash_codes_and_spread():
    assert java_hash_code(None) == 0
    assert java_hash_code(-5) == -5
    assert java_hash_code(2 ** 31) == -2 ** 31  # int32 wrap
    assert java_hash_code(Obj("x")) == IDENTITY_HASH == 1
    assert spread(0x12345678) == 0x12345678 ^ 0x1234
    assert spread(-1) == -1 ^ 0xFFFF


def test_identity_keys_insertion_order_up_to_ten():
    objs = [Obj("o%d" % i) for i in range(12)]
    s = JavaHashSet()
    for o in objs[:10]:
        s.add(o)
    assert s.to_array() == objs[:10]
    assert s.bin_layout()[0][1] == "list"


def test_identity_keys_treeify_at_eleven():
    objs = [Obj("o%d" % i) for i in range(12)]
    s = JavaHashSet()
    for o in objs[:11]:
        s.add(o)
    assert [o.label for o in s] == "o3 o0 o1 o2 o4 o5 o6 o7 o8 o9 o10".split()
    assert s.table_capacity() == 64 and s.bin_layout()[0][1] == "tree"
    s.add(objs[11])
    s.remove(objs[0])
    assert [o.label for o in s] == "o7 o3 o1 o2 o4 o5 o6 o8 o9 o10 o11".split()


def test_null_key_and_integer_bins():
    s = JavaHashSet()
    for k in (17, 1, 33, None, 16):
        s.add(k)
    assert s.to_array() == [None, 16, 17, 1, 33]


def test_colliding_strings_keep_list_order_below_threshold():
    s = JavaHashSet()
    for k in ("BB", "Aa", "AaAa", "BBBB", "AaBB", "BBAa", "SV", "A"):
        s.add(k)
    assert s.to_array() == ["BB", "Aa", "A", "SV", "AaAa", "BBBB", "AaBB", "BBAa"]


def test_hashmap_api():
    m = JavaHashMap()
    assert m.put(3, "a") is None
    assert m.put(19, "b") is None
    assert m.put(3, "c") == "a"  # existing key keeps its position
    assert m.keys() == [3, 19] and m.values() == ["c", "b"]
    assert m.get(19) == "b" and m.contains_key(3) and 19 in m and len(m) == 2
    assert m.remove(3) == "c" and m.remove(3) is None
    assert m.items() == [(19, "b")]
    m.clear()
    assert m.is_empty() and m.table_capacity() == 16


def test_resize_splits_preserving_order():
    m = JavaHashMap()
    keys = [1, 17, 33, 49, 2, 18, 3, 4, 5, 6, 7, 8, 9]  # 13 > threshold 12 -> resize to 32
    for k in keys:
        m.put(k, k)
    assert m.table_capacity() == 32
    assert m.keys() == [1, 33, 2, 3, 4, 5, 6, 7, 8, 9, 17, 49, 18]


@pytest.mark.skipif(os.environ.get("CD_JAVAHASH_LIVE") != "1", reason="set CD_JAVAHASH_LIVE=1 to run against a live JDK")
def test_live_jdk():
    env = dict(os.environ, CD_SKIP_BUILD=os.environ.get("CD_SKIP_BUILD", "1"))
    subprocess.check_call([sys.executable, "-B", os.path.join(REPO, "tools", "reference", "javahash_probe.py"),
                           "--check"], env=env)
