// Parity of docs/js/engine.js and docs/js/original.js with the Python package: every record
// of tests/fixtures/parity/*.json
// (generated by tools/gen_parity.py) must be reproduced exactly, and every witness the JS
// engine returns must pass the JS replay.  The classic scripts are loaded with node:vm into
// one context, as a browser would load them.  Run: npm test (node built-ins only).
"use strict";

const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

const ROOT = path.join(__dirname, "..", "..");
const PARITY = path.join(ROOT, "tests", "fixtures", "parity");

function loadScripts(names) {
  const ctx = vm.createContext({});
  for (const n of names) {
    const file = path.join(ROOT, "docs", "js", n);
    vm.runInContext(fs.readFileSync(file, "utf8"), ctx, { filename: file });
  }
  return ctx;
}

const ctx = loadScripts(["engine.js", "original.js"]);
const CD = ctx.CyberDetectives;

// values created in the vm realm have other prototypes: compare as plain JSON
const plain = (x) => (x === undefined ? null : JSON.parse(JSON.stringify(x)));

function makeRunner(file) {
  const cache = new Map();
  const getMap = (name) => {
    if (name === undefined || name === null) return null;
    if (!cache.has(name)) cache.set(name, CD.Map.fromDict(file.maps[name]));
    return cache.get(name);
  };
  const witnessesChecked = { n: 0 };

  function checkWitness(a, r, m) {
    if (r && r.consistent && r.compat === null && r.path && !("case" in r)) {
      CD.replay(m, r.path, a.history, { agents: a.agents, story: a.story,
                                        unreportedVisits: a.unreported_visits });
      witnessesChecked.n++;
    }
  }

  const fns = {
    map_from_dict(a) {
      const m = CD.Map.fromDict(a.dict);
      // Object.fromEntries makes own properties, also for names like "__proto__"
      const kinds = Object.fromEntries(m.features.concat(Array.from(m.beams.keys()),
        Array.from(m.regions.keys())).map((n) => [n, m.kind(n)]));
      const regionsOf = Object.fromEntries(Array.from(m.regionsOf.entries()));
      return { to_dict: m.toDict(), edges: m.edges(), adjacency: m.adjacency(),
               region_graph_edges: m.regionGraphEdges(), features: m.features, sides: m.sides,
               sensors: m.sensors, regions_of: regionsOf, kinds };
    },
    parse_story: (a) => CD.parseStory(a.story, getMap(a.map)),
    parse_history: (a) => CD.parseHistory(a.history, getMap(a.map), { checkNames: a.check_names })
      .map((e) => [e.sensor, e.kind]),
    history_to_string: (a) => CD.historyToString(a.events, getMap(a.map)),
    check_history: (a) => CD.checkHistory(getMap(a.map), a.events, a.agents),
    validate(a) {
      const m = getMap(a.map);
      const r = CD.validate(m, a.story, a.history, { agents: a.agents,
        unreportedVisits: a.unreported_visits, compat: a.compat === undefined ? null : a.compat });
      checkWitness(a, r, m);
      return r;
    },
    possible_positions: (a) => CD.possiblePositions(getMap(a.map), a.history, {
      story: a.story, agents: a.agents, unreportedVisits: a.unreported_visits, starts: a.starts }),
    validate_intervals: (a) => CD.validateIntervals(getMap(a.map), a.story, a.history, {
      case: a.case, agents: a.agents, unreportedVisits: a.unreported_visits }),
    shortest_superstory(a) {
      const m = getMap(a.map);
      const r = CD.shortestSuperstory(m, a.story, a.history, { anchored: a.anchored,
        agents: a.agents, unreportedVisits: a.unreported_visits });
      if (r) {
        CD.replay(m, r.path, a.history, { agents: a.agents, story: r.story,
                                          unreportedVisits: a.unreported_visits });
      }
      return r;
    },
    closest_story(a) {
      const m = getMap(a.map);
      const r = CD.closestStory(m, a.story, a.history, { agents: a.agents,
        unreportedVisits: a.unreported_visits });
      if (r) {
        CD.replay(m, r.path, a.history, { agents: a.agents, story: r.story,
                                          unreportedVisits: a.unreported_visits });
      }
      return r;
    },
    replay: (a) => CD.replay(getMap(a.map), a.path, a.history, { agents: a.agents,
      story: a.story, unreportedVisits: a.unreported_visits }),
    validate_compat: (a) => CD.original.validateCompat(file.maps[a.map], a.story, a.events, a.agents),
    javahash: (a) => javahashRun(a.kind, a.ops),
  };

  function run(c) {
    const fn = fns[c.fn];
    if (!fn) throw new Error("no runner for fn " + c.fn);
    try {
      return { return: plain(fn(c.args)) };
    } catch (e) {
      const err = { type: e.name, message: e.message };
      if (e.name === "JavaException") err.java = plain(e.describe());
      return { error: err, stack: e.stack };
    }
  }

  return { run, witnessesChecked };
}

// FNV-1a over UTF-8, as tools/gen_parity.py
function fnv1a(text) {
  let h = 0x811c9dc5;
  for (const b of Buffer.from(text, "utf8")) {
    h ^= b;
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(16).padStart(8, "0");
}

function javahashRun(kind, ops) {
  const s = new CD.original.JavaHashSet();
  const objs = new Map();
  const key = (tok) => {
    if (tok === "null") return null;
    if (kind === "int") return parseInt(tok, 10);
    if (kind === "str") return tok;
    if (!objs.has(tok)) objs.set(tok, { name: tok });
    return objs.get(tok);
  };
  const name = (k) => (k === null ? "null" : (typeof k === "object" ? k.name : String(k)));
  const sums = [];
  for (const op of ops) {
    const k = key(op.slice(1));
    if (op[0] === "+") s.add(k); else s.remove(k);
    sums.push(fnv1a(s.toArray().map(name).join(" ")));
  }
  return { fnv: sums, final: s.toArray().map(name), capacity: s.tableCapacity() };
}

function runFile(name) {
  const file = JSON.parse(fs.readFileSync(path.join(PARITY, name), "utf8"));
  const runner = makeRunner(file);
  const fails = [];
  for (const c of file.cases) {
    const got = runner.run(c);
    const stack = got.stack;
    delete got.stack;
    try {
      assert.deepStrictEqual(got, c.expect);
    } catch (e) {
      fails.push(c.id + " (" + c.fn + ")\n  args: " + JSON.stringify(c.args) +
                 "\n  want: " + JSON.stringify(c.expect) + "\n  got:  " + JSON.stringify(got) +
                 (stack && !c.expect.error ? "\n  " + stack.split("\n").slice(0, 4).join("\n  ") : ""));
    }
  }
  assert.ok(file.cases.length > 0, name + " has no cases");
  if (fails.length) {
    assert.fail(fails.length + " of " + file.cases.length + " records of " + name +
                " differ; first ones:\n" + fails.slice(0, 5).join("\n"));
  }
  return runner.witnessesChecked.n;
}

for (const name of ["maps.json", "inputs.json", "paper.json", "random_single.json",
                    "random_multi.json", "problems.json", "replay.json", "compat.json", "names.json"]) {
  test("parity " + name, () => { runFile(name); });
}

test("every parity file is covered by a JS test", () => {
  const covered = new Set(["maps.json", "inputs.json", "paper.json", "random_single.json",
                           "random_multi.json", "problems.json", "replay.json", "compat.json", "names.json"]);
  for (const f of fs.readdirSync(PARITY)) {
    if (f.endsWith(".json")) assert.ok(covered.has(f), "no JS test reads " + f);
  }
});

test("API smoke: namespace, star_fig2 witness, errors", () => {
  assert.strictEqual(typeof CD.validate, "function");
  const m = CD.Map.fromDict(JSON.parse(fs.readFileSync(path.join(PARITY, "paper.json"), "utf8")).maps.star_fig2);
  const r = CD.validate(m, "ACBAC", "b1 o1 o1 o2 o2 b2");
  assert.strictEqual(r.consistent, true);
  assert.strictEqual(r.path_string, "AC[b1d][o1][o2]B[b2r]AC");
  assert.strictEqual(CD.validate(m, "ACBAC", "b1 o1 o1 o2 o2 b2", { agents: "multi" }).path_string,
                     "AC{o1}{o2}B[b2r]AC");
  assert.throws(() => CD.validate(m, "AZ", ""), (e) => e instanceof CD.InputError &&
                e instanceof CD.ValueError && e.name === "InputError");
  assert.throws(() => CD.replay(m, [], ""), (e) => e instanceof CD.InvalidPath);
  assert.deepStrictEqual(plain(CD.possiblePositions(m, "b1 o1 o1 o2 o2 b2", { story: "ACBAC" })),
                         [["A", "C", "R1", "R2"], ["C", "R1", "R2"], ["o1"], ["R3"], ["o2"],
                          ["B", "R4"], ["A", "C", "R1", "R2"]]);
});

test("JS-only input forms: Map, Set, Event and objects as Python's dict / tuple", () => {
  const m = CD.Map.fromDict(JSON.parse(fs.readFileSync(path.join(PARITY, "paper.json"), "utf8")).maps.star_fig2);
  const want = [["b1", "A"], ["o1", "A"]];
  const pairs = (h) => plain(CD.parseHistory(h, m)).map((e) => [e.sensor, e.kind]);
  assert.deepStrictEqual(pairs([new CD.Event("b1", "A"), new CD.Event("o1", "A")]), want);
  assert.deepStrictEqual(pairs([new Map([["sensor", "b1"], ["kind", "A"]]), { sensor: "o1", kind: "A" }]), want);
  // Python: parse_history({"b1": "A"}) and parse_history({"b1"}) / a generator raise the same text
  const err = (f) => { try { f(); } catch (e) { return e.name + ": " + e.message; } return "no error"; };
  assert.strictEqual(err(() => CD.parseHistory(new Map([["b1", "A"]]), m)),
                     "InputError: history must be a string or a list of events, got {'b1': 'A'}");
  assert.strictEqual(err(() => CD.parseHistory({ b1: "A" }, m)),
                     "InputError: history must be a string or a list of events, got {'b1': 'A'}");
  assert.ok(err(() => CD.parseHistory(new Set(["b1"]), m)).startsWith("InputError: history must be a string or a list"));
  assert.ok(err(() => CD.parseStory(new Set(["A"]), m)).startsWith("InputError: story must be a string or a list"));
  assert.strictEqual(err(() => CD.parseStory({ A: 1 }, m)),
                     "InputError: story must be a string or a list of room names, got {'A': 1}");
  // an inherited "sensor"/"kind" does not make an item a {sensor, kind} object
  const proto = Object.create({ sensor: "b1", kind: "A" });
  assert.ok(err(() => CD.parseHistory([proto], m)).includes("is not a (sensor, kind) pair"));
});

test("possiblePositions starts option", () => {
  const m = CD.Map.fromDict(JSON.parse(fs.readFileSync(path.join(PARITY, "paper.json"), "utf8")).maps.star_fig2);
  assert.deepStrictEqual(plain(CD.possiblePositions(m, "")), [["A", "B", "C", "R1", "R2", "R4"]]);
  assert.deepStrictEqual(plain(CD.possiblePositions(m, "", { starts: "anywhere" })),
                         [["A", "B", "C", "R1", "R2", "R3", "R4"]]);
  assert.throws(() => CD.possiblePositions(m, "", { starts: "regions" }),
                (e) => e.name === "ValueError" && e.message === "starts must be 'rooms' or 'anywhere', got 'regions'");
  assert.throws(() => CD.possiblePositions(m, "", { story: "A", starts: "anywhere" }),
                (e) => e.name === "ValueError" && /needs story=None/.test(e.message));
});

test("names are data: Object.prototype members and __proto__ as map names", () => {
  const m = CD.Map.fromDict({ name: "p", rooms: ["__proto__", "constructor"], beams: { toString: ["hasOwnProperty", "valueOf"] },
                              occupancy: ["__defineGetter__"],
                              regions: { __lookupGetter__: ["__proto__", "hasOwnProperty", "__defineGetter__"],
                                         isPrototypeOf: ["constructor", "valueOf", "__defineGetter__"] } });
  const d = m.toDict();
  assert.deepStrictEqual(Object.keys(d.regions), ["__lookupGetter__", "isPrototypeOf"]);
  assert.deepStrictEqual(Object.keys(m.adjacency()), ["__proto__", "constructor", "hasOwnProperty", "valueOf", "__defineGetter__"]);
  assert.strictEqual(Object.getPrototypeOf(m.adjacency()), Object.getPrototypeOf(d));
  const r = CD.validate(m, ["__proto__", "constructor"], "toString", { agents: "multi" });
  assert.strictEqual(r.path_string, "__proto__[hasOwnProperty]constructor");
  assert.strictEqual(CD.historyToString(CD.parseHistory("__defineGetter__ __defineGetter__", m), m),
                     "__defineGetter__ __defineGetter__");
  // digit names: toDict writes the pair form, which keeps the order
  const g = CD.Map.fromDict({ name: "g", rooms: ["A", "B"], beams: [["9", ["bu", "bd"]], ["2", ["cu", "cd"]]],
                              occupancy: [], regions: { R: ["A", "bu", "cu"], S: ["B", "bd", "cd"] } });
  assert.deepStrictEqual(plain(g.toDict().beams), [["9", ["bu", "bd"]], ["2", ["cu", "cd"]]]);
  assert.deepStrictEqual(plain(g.sensors), ["9", "2"]);
  assert.deepStrictEqual(plain(CD.Map.fromDict(g.toDict()).toDict()), plain(g.toDict()));
});
