#!/usr/bin/env python3
"""Merge harness results into golden fixture files (called by regen_golden.sh).

    python3 tools/reference/make_golden.py --cases DIR --results DIR --meta META.json \
        --alt LABEL=DIR ... --out tests/fixtures/golden [--max-bytes 1500000]

For every DIR/<set>.cases.json it reads the canonical results RESULTS/<set>.json and the
results of each alternative hash setting ALTDIR/<set>.json, and writes
OUT/<set>.json (or OUT/<set>_partNN.json when a file would exceed --max-bytes) plus
OUT/summary.json. A field is "order_dependent" when at least one alternative setting
produced a different value than the canonical run (so `false` means "not observed to
change", `true` is proven by a witness).
"""
import argparse
import collections
import hashlib
import json
import os
import sys

RESULT_FIELDS = ["return", "stdout", "exception", "aliases", "graph_dump", "graph_dump_exception",
                 "call_exception", "stderr"]
STDOUT_TRIM = 60000  # characters; longer stdout traces keep head + tail + sha256


def load(p):
    with open(p, encoding="utf-8") as f:
        return json.load(f)


def diff_paths(a, b, path, out):
    """Collect leaf paths where a and b differ."""
    if isinstance(a, dict) and isinstance(b, dict) and a.keys() == b.keys():
        for k in a:
            diff_paths(a[k], b[k], "%s.%s" % (path, k), out)
    elif isinstance(a, list) and isinstance(b, list) and len(a) == len(b):
        for i, (x, y) in enumerate(zip(a, b)):
            diff_paths(x, y, "%s[%d]" % (path, i), out)
    elif a != b:
        out.add(path)


def trim(s):
    if s is None or len(s) <= STDOUT_TRIM:
        return s, None
    h = hashlib.sha256(s.encode("utf-8")).hexdigest()
    keep = STDOUT_TRIM // 2
    info = {"trimmed": True, "length": len(s), "sha256": h, "lines": s.count("\n")}
    return s[:keep] + "\n...[trimmed by make_golden.py]...\n" + s[-keep:], info


def dump_file(path, header, maps, cases):
    with open(path, "w", encoding="ascii", newline="\n") as f:
        f.write("{\n")
        f.write('"header": %s,\n' % json.dumps(header, ensure_ascii=True, sort_keys=False, indent=1))
        f.write('"maps": [\n')
        for i, m in enumerate(maps):
            f.write(json.dumps(m, ensure_ascii=True, separators=(",", ":")))
            f.write(",\n" if i + 1 < len(maps) else "\n")
        f.write("],\n")
        f.write('"cases": [\n')
        for i, c in enumerate(cases):
            f.write(json.dumps(c, ensure_ascii=True, separators=(",", ":")))
            f.write(",\n" if i + 1 < len(cases) else "\n")
        f.write("]\n}\n")


def occ_names(cf, c):
    """Occupancy sensor names of the case's map (STAR o1/o2 for game and applet cases)."""
    m = c.get("map")
    if isinstance(m, dict):
        return set(m.get("occupancy", []))
    for mp in cf["maps"]:
        if mp["name"] == m:
            return set(mp.get("occupancy", []))
    return {"o1", "o2"}


def exc_key(e):
    return "%s @ %s" % (e["class"], e["origin_frame"] or e["top_frame"])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cases", required=True)
    ap.add_argument("--results", required=True)
    ap.add_argument("--meta", required=True)
    ap.add_argument("--alt", action="append", default=[], help="LABEL=DIR")
    ap.add_argument("--alt-desc", action="append", default=[], help="LABEL=description")
    ap.add_argument("--out", required=True)
    ap.add_argument("--max-bytes", type=int, default=1500000)
    ap.add_argument("--original-commit", required=True)
    ap.add_argument("--canonical-flags", required=True)
    ap.add_argument("--paper-crosscheck", metavar="REPO",
                    help="add the crosscheck block to paper_cases.json (paper_crosscheck.py) before sizing it")
    a = ap.parse_args()

    meta = load(a.meta)
    alts = [x.split("=", 1) for x in a.alt]
    alt_desc = dict(x.split("=", 1) for x in a.alt_desc)
    os.makedirs(a.out, exist_ok=True)
    sets = sorted(f[:-len(".cases.json")] for f in os.listdir(a.cases) if f.endswith(".cases.json"))
    order = ["builtin", "star_random_single", "star_random_multi", "random_maps", "subgraphs", "applet",
             "paper_cases", "edge_cases"]
    sets.sort(key=lambda s: (order.index(s) if s in order else 99, s))

    summary = collections.OrderedDict()
    summary["note"] = ("Statistics of the golden fixtures; generated by tools/reference/make_golden.py. "
                       "order_dependent counts are lower bounds (fields that changed under at least one "
                       "alternative hash setting).")
    summary["sets"] = collections.OrderedDict()
    totals = collections.Counter()
    tot_exc = collections.Counter()
    tot_od = collections.Counter()
    written = []
    problems = []

    for s in sets:
        cf = load(os.path.join(a.cases, s + ".cases.json"))
        canon = load(os.path.join(a.results, s + ".json"))
        alt_res = [(lab, {r["id"]: r for r in load(os.path.join(d, s + ".json"))}) for lab, d in alts]
        assert len(canon) == len(cf["cases"]), s
        stats = collections.OrderedDict()
        exc_c = collections.Counter()
        verdict = collections.Counter()
        od_c = collections.Counter()
        n_od_cases = 0
        extra_crossings = []
        path_order_dep = []
        out_cases = []
        by_id = {}
        for c, r in zip(cf["cases"], canon):
            assert c["id"] == r["id"], (c["id"], r["id"])
            if "harness_error" in r:
                problems.append("%s: harness error: %s" % (c["id"], r["harness_error"]))
            exp = collections.OrderedDict()
            if r["op"] in ("validateAgentStory", "validateAgentStoryMulti") and r["exception"] is None:
                exp["consistent"] = r["return"]
            for k in RESULT_FIELDS:
                if k in r:
                    exp[k] = r[k]
            od = collections.OrderedDict((k, False) for k in RESULT_FIELDS if k in r)
            paths = set()
            for lab, ar in alt_res:
                x = ar[r["id"]]
                if "harness_error" in x:
                    problems.append("%s (%s): harness error: %s" % (c["id"], lab, x["harness_error"]))
                for k in od:
                    p = set()
                    diff_paths(r.get(k), x.get(k), k, p)
                    if p:
                        od[k] = True
                        paths |= p
            exp["order_dependent"] = od
            if paths:
                exp["order_dependent_paths"] = sorted(paths)
                n_od_cases += 1
            for k, v in od.items():
                if v:
                    od_c[k] += 1
            # trim gigantic traces (never return values)
            st, info = trim(exp.get("stdout"))
            if info:
                exp["stdout"] = st
                exp["stdout_trim"] = info
            oc = collections.OrderedDict(c)
            oc["expected"] = exp
            oc["verified_by"] = ("recorded from the original Java code by tools/reference/Harness.java "
                                 "(canonical JVM flags in header); not independently verified")
            out_cases.append(oc)
            by_id[c["id"]] = oc

            # statistics
            if r["exception"]:
                exc_c["%s: %s" % (r["op"], exc_key(r["exception"]))] += 1
            if "call_exception" in r:
                exc_c["%s (inside call): %s" % (r["op"], exc_key(r["call_exception"]))] += 1
            if r["op"] == "applet":
                for i, stp in enumerate(r["return"] or []):
                    if stp.get("exception"):
                        exc_c["applet step %s: %s" % (stp["action"], exc_key(stp["exception"]))] += 1
                    if stp["action"] == "run":
                        if stp.get("validate") is not None:
                            verdict["applet_%s=%s" % (stp["mode"], stp["validate"])] += 1
                        elif stp.get("exception"):
                            verdict["applet_%s=crash" % stp["mode"]] += 1
                        else:
                            verdict["applet_%s=no_run(%s)" % (stp["mode"], stp["result_text"])] += 1
            elif r["op"] in ("validateAgentStory", "validateAgentStoryMulti"):
                verdict["%s=%s" % (r["op"], "crash" if r["exception"] else r["return"])] += 1
            elif r["op"] in ("getAgentStory", "getAgentStoryStatuses"):
                verdict["%s=%s" % (r["op"], "crash" if r["exception"] else "returned")] += 1
            # B3: a path needs exactly one [..] per non-deactivation recording
            paths_to_check = []
            if r["op"] == "getAgentStory" and isinstance(r["return"], str) and "history" in c:
                paths_to_check.append((r["return"], c["history"]))
            if r["op"] == "applet":
                for stp in r["return"] or []:
                    if isinstance(stp.get("path"), str):
                        paths_to_check.append((stp["path"], stp["parsed_history"]))
            for pth, hist in paths_to_check:
                n_rec = sum(1 for sn, ev in hist if not (sn in occ_names(cf, c) and ev == "D"))
                if pth.count("[") != n_rec:
                    extra_crossings.append(c["id"])
            if od.get("return") and r["op"] == "getAgentStory":
                path_order_dep.append(c["id"])

        # applet pipeline vs direct validateAgentStory(Multi) on the same parsed input
        if s == "applet":
            cmp_ = collections.Counter()
            diffs = []
            for oc in out_cases:
                if not oc["id"].endswith("__direct"):
                    continue
                ap_case = by_id[oc["id"][:-len("__direct")]]
                st = ap_case["expected"]["return"][0]
                d = oc["expected"]
                av = "crash:" + st["exception"]["class"] if st.get("exception") else (
                    st["validate"] if st.get("validate") is not None else "no_run")
                dv = "crash:" + d["exception"]["class"] if d.get("exception") else d["return"]
                # parsed input must be identical (checks the Python mirror of the parser)
                same_input = (st.get("parsed_story") == [None if x not in ("A", "B", "C") else x for x in oc["story"]]
                              and st.get("parsed_history") == oc["history"]) if "parsed_story" in st else None
                key = "%s: applet=%s direct=%s%s" % (oc["mode"], av, dv,
                                                     "" if same_input in (True, None) else " (PARSE MISMATCH)")
                cmp_[key] += 1
                if av != dv or same_input is False:
                    diffs.append(ap_case["id"])
            stats["applet_vs_direct"] = collections.OrderedDict(sorted(cmp_.items()))
            stats["applet_vs_direct_differing_cases"] = diffs

        stats["num_cases"] = len(out_cases)
        stats["exceptions"] = collections.OrderedDict(sorted(exc_c.items()))
        stats["verdicts"] = collections.OrderedDict(sorted(verdict.items()))
        stats["order_dependent_fields"] = collections.OrderedDict(sorted(od_c.items()))
        stats["cases_with_order_dependent_output"] = n_od_cases
        stats["paths_with_wrong_number_of_crossings_B3"] = sorted(set(extra_crossings))
        stats["getAgentStory_return_order_dependent_B2"] = len(path_order_dep)
        totals["B3"] += len(set(extra_crossings))
        totals["B2"] += len(path_order_dep)
        summary["sets"][s] = stats
        totals["cases"] += len(out_cases)
        totals["cases_with_order_dependent_output"] += n_od_cases
        for k, v in exc_c.items():
            tot_exc[k.split(": ", 1)[1]] += v
        tot_od.update(od_c)

        header = collections.OrderedDict()
        header["kind"] = "golden"
        header["set"] = s
        header["description"] = ("Outputs of the original Java code (compat=\"original\"), bugs and crashes "
                                 "included. See tools/reference/README.md and tests/fixtures/golden/README.md.")
        header["generator"] = cf["header"]["generator"]
        header["generator_version"] = cf["header"]["generator_version"]
        header["seed"] = cf["header"]["seed"]
        header["set_seed"] = cf["header"]["set_seed"]
        header["harness"] = "tools/reference/Harness.java"
        header["harness_version"] = meta["harness_version"]
        header["original_repo"] = "https://github.com/arc-l/cyber-detective.git"
        header["original_commit"] = a.original_commit
        header["jdk"] = collections.OrderedDict(
            (k, meta[k]) for k in ["java.version", "java.runtime.version", "java.vm.name", "java.vm.version",
                                   "java.vendor", "os.arch"])
        header["jvm_flags"] = a.canonical_flags
        header["jvm_input_arguments"] = meta["jvm_input_arguments"]
        header["isolation"] = ("all cases of a file run in one JVM; each case builds a fresh game, has its own "
                               "captured stdout/stderr and catches every Throwable. Under -XX:hashCode=2 every "
                               "identity hash is 1, so this equals one fresh JVM per case "
                               "(checked by regen_golden.sh).")
        header["order_dependence"] = collections.OrderedDict()
        header["order_dependence"]["method"] = ("each file was also run under the alternative identity-hash "
                                                "settings below; expected.order_dependent[field] is true iff "
                                                "some alternative changed that field")
        header["order_dependence"]["alternatives"] = [
            collections.OrderedDict([("label", lab), ("setting", alt_desc.get(lab, ""))]) for lab, _ in alts]
        header["stdout_trim_chars"] = STDOUT_TRIM

        # write, splitting if needed
        base = os.path.join(a.out, s + ".json")
        parts = [out_cases]
        while True:
            sizes = []
            for k, part in enumerate(parts):
                h = collections.OrderedDict(header)
                if len(parts) > 1:
                    h["part"] = "%d/%d" % (k + 1, len(parts))
                h["num_cases"] = len(part)
                tmp = base + ".tmp"
                dump_file(tmp, h, cf["maps"], part)
                sizes.append(os.path.getsize(tmp))
                os.remove(tmp)
            if max(sizes) <= a.max_bytes:
                break
            n = len(parts) + 1
            per = (len(out_cases) + n - 1) // n
            parts = [out_cases[i:i + per] for i in range(0, len(out_cases), per)]
        for k, part in enumerate(parts):
            h = collections.OrderedDict(header)
            if len(parts) > 1:
                h["part"] = "%d/%d" % (k + 1, len(parts))
            h["num_cases"] = len(part)
            name = s + (".json" if len(parts) == 1 else "_part%02d.json" % (k + 1))
            dump_file(os.path.join(a.out, name), h, cf["maps"], part)
            if s == "paper_cases" and a.paper_crosscheck:
                import paper_crosscheck
                paper_crosscheck.crosscheck(a.paper_crosscheck, os.path.join(a.out, name),
                                            os.path.join(a.out, name))
            written.append((name, os.path.getsize(os.path.join(a.out, name)), len(part)))

    summary["totals"] = collections.OrderedDict([
        ("cases", totals["cases"]),
        ("cases_with_order_dependent_output", totals["cases_with_order_dependent_output"]),
        ("cases_whose_recorded_path_has_wrong_number_of_crossings_B3", totals["B3"]),
        ("getAgentStory_cases_whose_path_is_order_dependent_B2", totals["B2"]),
        ("exceptions", collections.OrderedDict(sorted(tot_exc.items()))),
        ("order_dependent_fields", collections.OrderedDict(sorted(tot_od.items()))),
    ])
    summary["files"] = [collections.OrderedDict([("file", n), ("bytes", b), ("cases", c)]) for n, b, c in written]
    with open(os.path.join(a.out, "summary.json"), "w", encoding="ascii", newline="\n") as f:
        f.write(json.dumps(summary, ensure_ascii=True, indent=1) + "\n")
    for n, b, c in written:
        print("%-32s %8d bytes %5d cases" % (n, b, c), file=sys.stderr)
    if problems:
        print("\n".join(problems), file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
